-- This file is used to setup the database tables and load the NIBRS
-- code lookup tables. It only needs to be run once before you load
-- any data tables using postgres_load.sql

SET statement_timeout = 0;
SET lock_timeout = 0;
-- SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--Create PKs and FKs
--PKS

  ALTER TABLE ONLY PUBLIC.NIBRS_SUSPECTED_DRUG ADD CONSTRAINT NIBRS_SUSPECTED_DRUG_PK PRIMARY KEY (NIBRS_SUSPECTED_DRUG_ID);;

  ALTER TABLE ONLY PUBLIC.NIBRS_RELATIONSHIP ADD CONSTRAINT NIBRS_RELATIONSHIP_PK PRIMARY KEY (RELATIONSHIP_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_DRUG_MEASURE_TYPE ADD CONSTRAINT NIBRS_DRUG_MEASURE_TYPE_PK PRIMARY KEY (DRUG_MEASURE_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_USING_LIST ADD CONSTRAINT NIBRS_SUSPECTED_USING_PK PRIMARY KEY (SUSPECT_USING_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_PROP_LOSS_TYPE ADD CONSTRAINT NIBRS_PROP_LOSS_TYPE_PK PRIMARY KEY (PROP_LOSS_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ETHNICITY ADD CONSTRAINT NIBRS_ETH_PK PRIMARY KEY (ETHNICITY_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_PROPERTY ADD CONSTRAINT NIBRS_PROPERTY_PK PRIMARY KEY (PROPERTY_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_CRIMINAL_ACT ADD CONSTRAINT NIBRS_CRIMINAL_ACT_PK PRIMARY KEY (CRIMINAL_ACT_ID, OFFENSE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_OFFENSE_TYPE ADD CONSTRAINT NIBRS_OFFENSE_TYPE_PK PRIMARY KEY (offense_code);

  ALTER TABLE ONLY PUBLIC.NIBRS_CRIMINAL_ACT_TYPE ADD CONSTRAINT NIBRS_CRIMINAL_ACT_TYPE_PK PRIMARY KEY (CRIMINAL_ACT_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_PROPERTY_DESC ADD CONSTRAINT NIBRS_PROPERTY_DESC_PK PRIMARY KEY (property_id, prop_desc_id);

  ALTER TABLE ONLY PUBLIC.NIBRS_INCIDENT ADD CONSTRAINT NIBRS_INCIDENT_PK PRIMARY KEY (INCIDENT_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_BIAS_MOTIVATION ADD CONSTRAINT NIBRS_BIAS_MOTIVATION_PK PRIMARY KEY (BIAS_ID, OFFENSE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_SUSPECT_USING ADD CONSTRAINT NIBRS_SUSPECT_USING_PK PRIMARY KEY (SUSPECT_USING_ID, OFFENSE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_TYPE ADD CONSTRAINT NIBRS_VICTIM_TYPE_PK PRIMARY KEY (VICTIM_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_INJURY ADD CONSTRAINT NIBRS_INJURY_PK PRIMARY KEY (INJURY_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_OFFENDER ADD CONSTRAINT NIBRS_OFFENDER_PK PRIMARY KEY (OFFENDER_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_CIRCUMSTANCES ADD CONSTRAINT NIBRS_CIRCUMSTANCES_PK PRIMARY KEY (CIRCUMSTANCES_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ACTIVITY_TYPE ADD CONSTRAINT NIBRS_ACTIVITY_TYPE_PK PRIMARY KEY (ACTIVITY_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_PK PRIMARY KEY (ARRESTEE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE_GROUPB ADD CONSTRAINT NIBRS_ARRESTEE_GROUPB_PK PRIMARY KEY (GROUPB_ARRESTEE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_WEAPON_TYPE ADD CONSTRAINT NIBRS_WEAPON_TYPE_PK PRIMARY KEY (WEAPON_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_BIAS_LIST ADD CONSTRAINT NIBRS_BIAS_LIST_PK PRIMARY KEY (BIAS_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARREST_TYPE ADD CONSTRAINT NIBRS_ARREST_TYPE_PK PRIMARY KEY (ARREST_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_INJURY ADD CONSTRAINT NIBRS_VICTIM_INJURY_PK PRIMARY KEY (VICTIM_ID, INJURY_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_OFFENSE ADD CONSTRAINT NIBRS_OFFENSE_PK PRIMARY KEY (OFFENSE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_OFFENDER_REL ADD CONSTRAINT NIBRS_VICTIM_OFFENDER_REL_PK PRIMARY KEY (victim_id, offender_id);

  ALTER TABLE ONLY PUBLIC.NIBRS_CLEARED_EXCEPT ADD CONSTRAINT NIBRS_CLEARED_EXCEPT_PK PRIMARY KEY (CLEARED_EXCEPT_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_PK PRIMARY KEY (VICTIM_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_MONTH ADD CONSTRAINT NIBRS_MONTH_PK PRIMARY KEY (did);

  ALTER TABLE ONLY PUBLIC.NIBRS_AGE ADD CONSTRAINT NIBRS_AGE_PK PRIMARY KEY (AGE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_PROP_DESC_TYPE ADD CONSTRAINT NIBRS_PROP_DESC_TYPE_PK PRIMARY KEY (PROP_DESC_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_CIRCUMSTANCES ADD CONSTRAINT NIBRS_VICTIM_CIRCUMSTANCES_PK PRIMARY KEY (VICTIM_ID, CIRCUMSTANCES_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE_WEAPON ADD CONSTRAINT NIBRS_ARRESTEE_WEAPON_PK PRIMARY KEY (arrestee_id, weapon_id);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE_GROUPB_WEAPON ADD CONSTRAINT NIBRS_ARRESTEE_GROUPB_WEAPON_PK PRIMARY KEY (groupb_arrestee_id, weapon_id);

  ALTER TABLE ONLY PUBLIC.NIBRS_SUSPECTED_DRUG_TYPE ADD CONSTRAINT NIBRS_SUSPECTED_DRUG_TYPE_PK PRIMARY KEY (SUSPECTED_DRUG_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_OFFENSE ADD CONSTRAINT NIBRS_VICTIM_OFFENSE_PK PRIMARY KEY (VICTIM_ID, OFFENSE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_LOCATION_TYPE ADD CONSTRAINT NIBRS_LOCATION_TYPE_PK PRIMARY KEY (LOCATION_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ASSIGNMENT_TYPE ADD CONSTRAINT NIBRS_ASSIGN_TYPE_PK PRIMARY KEY (ASSIGNMENT_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_WEAPON ADD CONSTRAINT NIBRS_WEAPON_PK PRIMARY KEY (weapon_id, offense_id);

  ALTER TABLE ONLY PUBLIC.REF_RACE ADD CONSTRAINT REF_RACE_PK PRIMARY KEY (RACE_ID);

  ALTER TABLE ONLY PUBLIC.REF_STATE ADD CONSTRAINT REF_STATE_PK PRIMARY KEY (STATE_ID);

  ALTER TABLE ONLY PUBLIC.AGENCIES ADD CONSTRAINT AGENCIES_PK PRIMARY KEY (agency_id);

  ALTER TABLE ONLY PUBLIC.NIBRS_JUSTIFIABLE_FORCE ADD CONSTRAINT NIBRS_JUSTIFIABLE_FORCE_PK PRIMARY KEY (JUSTIFIABLE_FORCE_ID);
