-- This file is used to setup the database tables and load the NIBRS
-- code lookup tables. It only needs to be run once before you load
-- any data tables using postgres_load.sql

SET statement_timeout = 0;
SET lock_timeout = 0;
-- SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--Create PKs and FKs
  -- FKs

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE_WEAPON ADD CONSTRAINT NIBRS_ARREST_WEAP_ARREST_FK FOREIGN KEY (ARRESTEE_ID)
	  REFERENCES PUBLIC.NIBRS_ARRESTEE (ARRESTEE_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE_WEAPON ADD CONSTRAINT NIBRS_ARREST_WEAP_TYPE_FK FOREIGN KEY (NIBRS_ARRESTEE_WEAPON_ID)
	  REFERENCES PUBLIC.NIBRS_WEAPON_TYPE (WEAPON_ID);
  
  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE_GROUPB_WEAPON ADD CONSTRAINT NIBRS_ARREST_GB_WEAP_ARREST_FK FOREIGN KEY (GROUPB_ARRESTEE_ID)
	  REFERENCES PUBLIC.NIBRS_ARRESTEE_GROUPB (GROUPB_ARRESTEE_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE_GROUPB_WEAPON ADD CONSTRAINT NIBRS_ARREST_GB_WEAP_TYPE_FK FOREIGN KEY (WEAPON_ID)
	  REFERENCES PUBLIC.NIBRS_WEAPON_TYPE (WEAPON_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_PROPERTY_DESC ADD CONSTRAINT NIBRS_PROP_DESC_PROP_FK FOREIGN KEY (PROPERTY_ID)
	  REFERENCES PUBLIC.NIBRS_PROPERTY (PROPERTY_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_PROPERTY_DESC ADD CONSTRAINT NIBRS_PROP_DESC_TYPE_FK FOREIGN KEY (PROP_DESC_ID)
	  REFERENCES PUBLIC.NIBRS_PROP_DESC_TYPE (PROP_DESC_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_AGE_FK FOREIGN KEY (AGE_ID)
	  REFERENCES PUBLIC.NIBRS_AGE (AGE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_ARREST_TYPE_FK FOREIGN KEY (ARREST_TYPE_ID)
	  REFERENCES PUBLIC.NIBRS_ARREST_TYPE (ARREST_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_ETHNICITY_FK FOREIGN KEY (ETHNICITY_ID)
	  REFERENCES PUBLIC.NIBRS_ETHNICITY (ETHNICITY_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_INC_FK FOREIGN KEY (INCIDENT_ID)
	  REFERENCES PUBLIC.NIBRS_INCIDENT (INCIDENT_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_RACE_FK FOREIGN KEY (RACE_ID)
	  REFERENCES PUBLIC.REF_RACE (RACE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE ADD CONSTRAINT NIBRS_ARRESTEE_OFFENSE_TYPE_FK FOREIGN KEY (offense_code)
	  REFERENCES PUBLIC.NIBRS_OFFENSE_TYPE (offense_code);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE_GROUPB ADD CONSTRAINT NIBRS_ARRESTEE_GB_AGE_FK FOREIGN KEY (AGE_ID)
	  REFERENCES PUBLIC.NIBRS_AGE (AGE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE_GROUPB ADD CONSTRAINT NIBRS_ARRESTEE_GB_ARREST_TYPE_FK FOREIGN KEY (ARREST_TYPE_ID)
	  REFERENCES PUBLIC.NIBRS_ARREST_TYPE (ARREST_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE_GROUPB ADD CONSTRAINT NIBRS_ARRESTEE_GB_ETHNICITY_FK FOREIGN KEY (ETHNICITY_ID)
	  REFERENCES PUBLIC.NIBRS_ETHNICITY (ETHNICITY_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE_GROUPB ADD CONSTRAINT NIBRS_ARRESTEE_GB_RACE_FK FOREIGN KEY (RACE_ID)
	  REFERENCES PUBLIC.REF_RACE (RACE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_ARRESTEE_GROUPB ADD CONSTRAINT NIBRS_ARRESTEE_GB_OFFENSE_TYPE_FK FOREIGN KEY (offense_code)
	  REFERENCES PUBLIC.NIBRS_OFFENSE_TYPE (offense_code);

  ALTER TABLE ONLY PUBLIC.NIBRS_SUSPECTED_DRUG ADD CONSTRAINT NIBRS_SUSP_DRUG_MEAS_TYPE_FK FOREIGN KEY (DRUG_MEASURE_TYPE_ID)
	  REFERENCES PUBLIC.NIBRS_DRUG_MEASURE_TYPE (DRUG_MEASURE_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_SUSPECTED_DRUG ADD CONSTRAINT NIBRS_SUSP_DRUG_PROP_FK FOREIGN KEY (PROPERTY_ID)
	  REFERENCES PUBLIC.NIBRS_PROPERTY (PROPERTY_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_SUSPECTED_DRUG ADD CONSTRAINT NIBRS_SUSP_DRUG_TYPE_FK FOREIGN KEY (SUSPECTED_DRUG_TYPE_ID)
	  REFERENCES PUBLIC.NIBRS_SUSPECTED_DRUG_TYPE (SUSPECTED_DRUG_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_PROPERTY ADD CONSTRAINT NIBRS_PROPERTY_INC_FK FOREIGN KEY (INCIDENT_ID)
	  REFERENCES PUBLIC.NIBRS_INCIDENT (INCIDENT_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_PROPERTY ADD CONSTRAINT NIBRS_PROPERTY_LOSS_TYPE_FK FOREIGN KEY (PROP_LOSS_ID)
	  REFERENCES PUBLIC.NIBRS_PROP_LOSS_TYPE (PROP_LOSS_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_CRIMINAL_ACT ADD CONSTRAINT NIBRS_CRIMINAL_ACT_OFFENSE_FK FOREIGN KEY (OFFENSE_ID)
	  REFERENCES PUBLIC.NIBRS_OFFENSE (OFFENSE_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_CRIMINAL_ACT ADD CONSTRAINT NIBRS_CRIMINAL_ACT_TYPE_FK FOREIGN KEY (CRIMINAL_ACT_ID)
	  REFERENCES PUBLIC.NIBRS_CRIMINAL_ACT_TYPE (CRIMINAL_ACT_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_OFFENDER ADD CONSTRAINT NIBRS_OFFENDER_AGE_FK FOREIGN KEY (AGE_ID)
	  REFERENCES PUBLIC.NIBRS_AGE (AGE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_OFFENDER ADD CONSTRAINT NIBRS_OFFENDER_ETHNICITY_FK FOREIGN KEY (ETHNICITY_ID)
	  REFERENCES PUBLIC.NIBRS_ETHNICITY (ETHNICITY_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_OFFENDER ADD CONSTRAINT NIBRS_OFFENDER_NIBRS_INCI_FK1 FOREIGN KEY (INCIDENT_ID)
	  REFERENCES PUBLIC.NIBRS_INCIDENT (INCIDENT_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_OFFENDER ADD CONSTRAINT NIBRS_OFFENDER_RACE_FK FOREIGN KEY (RACE_ID)
	  REFERENCES PUBLIC.REF_RACE (RACE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_INJURY ADD CONSTRAINT NIBRS_VIC_INJURY_NIBRS_INJ_FK FOREIGN KEY (INJURY_ID)
	  REFERENCES PUBLIC.NIBRS_INJURY (INJURY_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_INJURY ADD CONSTRAINT NIBRS_VIC_INJURY_NIBRS_VIC_FK FOREIGN KEY (VICTIM_ID)
	  REFERENCES PUBLIC.NIBRS_VICTIM (VICTIM_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_WEAPON ADD CONSTRAINT NIBRS_WEAP_WEAP_TYPE_FK FOREIGN KEY (WEAPON_ID)
	  REFERENCES PUBLIC.NIBRS_WEAPON_TYPE (WEAPON_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_WEAPON ADD CONSTRAINT NIBRS_WEAP_OFF_FK FOREIGN KEY (OFFENSE_ID)
	  REFERENCES PUBLIC.NIBRS_OFFENSE (OFFENSE_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_CIRCUMSTANCES ADD CONSTRAINT NIBRS_VIC_CIRC_NIBRS_VIC_FK FOREIGN KEY (VICTIM_ID)
	  REFERENCES PUBLIC.NIBRS_VICTIM (VICTIM_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_CIRCUMSTANCES ADD CONSTRAINT NIBRS_VICTIM_CIRC_JUST_HOM_FK FOREIGN KEY (JUSTIFIABLE_FORCE_ID)
	  REFERENCES PUBLIC.NIBRS_JUSTIFIABLE_FORCE (JUSTIFIABLE_FORCE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_CIRCUMSTANCES ADD CONSTRAINT NIBRS_VIC_CIRC_NIBRS_CIRC_FK FOREIGN KEY (CIRCUMSTANCES_ID)
	  REFERENCES PUBLIC.NIBRS_CIRCUMSTANCES (CIRCUMSTANCES_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_SUSPECT_USING ADD CONSTRAINT NIBRS_SUSPECT_USING_OFF_FK FOREIGN KEY (OFFENSE_ID)
	  REFERENCES PUBLIC.NIBRS_OFFENSE (OFFENSE_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_SUSPECT_USING ADD CONSTRAINT NIBRS_SUSPECT_USING_LIST_FK FOREIGN KEY (SUSPECT_USING_ID)
	  REFERENCES PUBLIC.NIBRS_USING_LIST (SUSPECT_USING_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_OFFENSE ADD CONSTRAINT NIBRS_OFFENSE_INC_FK1 FOREIGN KEY (INCIDENT_ID)
	  REFERENCES PUBLIC.NIBRS_INCIDENT (INCIDENT_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_OFFENSE ADD CONSTRAINT NIBRS_OFFENSE_LOC_TYPE_FK FOREIGN KEY (LOCATION_ID)
	  REFERENCES PUBLIC.NIBRS_LOCATION_TYPE (LOCATION_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_OFFENSE ADD CONSTRAINT NIBRS_OFFENSE_OFF_TYPE_FK FOREIGN KEY (offense_code)
	  REFERENCES PUBLIC.NIBRS_OFFENSE_TYPE (offense_code);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_OFFENDER_REL ADD CONSTRAINT NIBRS_VICTIM_OFF_REL_VIC_FK FOREIGN KEY (VICTIM_ID)
	  REFERENCES PUBLIC.NIBRS_VICTIM (VICTIM_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_OFFENDER_REL ADD CONSTRAINT NIBRS_VICTIM_OFF_REL_OFF_FK FOREIGN KEY (OFFENDER_ID)
	  REFERENCES PUBLIC.NIBRS_OFFENDER (OFFENDER_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_OFFENDER_REL ADD CONSTRAINT NIBRS_VICTIM_OFF_REL_REL_FK FOREIGN KEY (RELATIONSHIP_ID)
	  REFERENCES PUBLIC.NIBRS_RELATIONSHIP (RELATIONSHIP_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIMS_VIC_TYPE_FK FOREIGN KEY (VICTIM_TYPE_ID)
	  REFERENCES PUBLIC.NIBRS_VICTIM_TYPE (VICTIM_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_ACT_TYPE_FK FOREIGN KEY (ACTIVITY_TYPE_ID)
	  REFERENCES PUBLIC.NIBRS_ACTIVITY_TYPE (ACTIVITY_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_AGE_FK FOREIGN KEY (AGE_ID)
	  REFERENCES PUBLIC.NIBRS_AGE (AGE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_ASSIGN_TYPE_FK FOREIGN KEY (ASSIGNMENT_TYPE_ID)
	  REFERENCES PUBLIC.NIBRS_ASSIGNMENT_TYPE (ASSIGNMENT_TYPE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_ETHNICITY_FK FOREIGN KEY (ETHNICITY_ID)
	  REFERENCES PUBLIC.NIBRS_ETHNICITY (ETHNICITY_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_RACE_FK FOREIGN KEY (RACE_ID)
	  REFERENCES PUBLIC.REF_RACE (RACE_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM ADD CONSTRAINT NIBRS_VICTIM_INC_FK FOREIGN KEY (INCIDENT_ID)
	  REFERENCES PUBLIC.NIBRS_INCIDENT (INCIDENT_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_MONTH ADD CONSTRAINT NIBRS_MONTH_AGENCY_FK FOREIGN KEY (AGENCY_ID)
	  REFERENCES PUBLIC.AGENCIES (AGENCY_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_INCIDENT ADD CONSTRAINT NIBRS_INCIDENT_AGENCY_FK FOREIGN KEY (AGENCY_ID)
	  REFERENCES PUBLIC.AGENCIES (AGENCY_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_INCIDENT ADD CONSTRAINT NIBRS_INCIDENT_CLEAR_EX_FK FOREIGN KEY (CLEARED_EXCEPT_ID)
	  REFERENCES PUBLIC.NIBRS_CLEARED_EXCEPT (CLEARED_EXCEPT_ID);

  ALTER TABLE ONLY PUBLIC.NIBRS_INCIDENT ADD CONSTRAINT NIBRS_INCIDENT_MONTH_FK FOREIGN KEY (did)
	  REFERENCES PUBLIC.NIBRS_MONTH (did) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_OFFENSE ADD CONSTRAINT NIBRS_VIC_OFF_NIBRS_VIC_FK FOREIGN KEY (VICTIM_ID)
	  REFERENCES PUBLIC.NIBRS_VICTIM (VICTIM_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_VICTIM_OFFENSE ADD CONSTRAINT NIBRS_VIC_OFF_NIBRS_OFF_FK FOREIGN KEY (OFFENSE_ID)
	  REFERENCES PUBLIC.NIBRS_OFFENSE (OFFENSE_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_BIAS_MOTIVATION ADD CONSTRAINT NIBRS_BIAS_MOT_OFFENSE_FK FOREIGN KEY (OFFENSE_ID)
	  REFERENCES PUBLIC.NIBRS_OFFENSE (OFFENSE_ID) ON DELETE CASCADE;

  ALTER TABLE ONLY PUBLIC.NIBRS_BIAS_MOTIVATION ADD CONSTRAINT NIBRS_BIAS_MOT_LIST_FK FOREIGN KEY (BIAS_ID)
	  REFERENCES PUBLIC.NIBRS_BIAS_LIST (BIAS_ID);
